#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EcardQuery.Resource", IsApplication=true)]

namespace EcardQuery
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int square44x44logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int HistoryInquiry_EndDateBlock = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int HistoryInquiry_EndDateButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int HistoryInquiry_InquireButton = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int HistoryInquiry_StartDateBlock = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int HistoryInquiry_StartDateButton = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int Main_IdBox = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int Main_LoginButton = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int Main_PasswdBox = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int Main_ProgressBar = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int Main_RandBox = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Main_RandImage = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int Main_StatusText = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int MeCenter_BalanceBlock = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int MeCenter_HistoryInquiryButton = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int MeCenter_LogOutButton = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int MeCenter_RealtimeInquiryButton = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int RealtimeInquiry_InquireButton = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int Result_EmptyHint = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Result_MainList = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int Result_ProgressBar = 2131034132;
			
			// aapt resource value: 0x7f05001a
			public const int TransactionGroup_ChildrenList = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int TransactionGroup_TitleText = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int Transaction_BalanceText = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int Transaction_DeltaText = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Transaction_SubsystemText = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int Transaction_TimeText = 2131034133;
			
			// aapt resource value: 0x7f05000c
			public const int textView1 = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HistoryInquiry = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MeCenter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RealtimeInquiry = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Result = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TransactionDisplay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TransactionGroup = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int AppName = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int HistoryInquiry_EndDate = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int HistoryInquiry_Select = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int HistoryInquiry_StartDate = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int Inquiry_Inquire = 2130968591;
			
			// aapt resource value: 0x7f040001
			public const int Main_Id = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Main_Login = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Main_Pass = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Main_Rand = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int MeCenter_Balance = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int MeCenter_BalanceAcquireFailed = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int MeCenter_BalanceAcquiring = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int MeCenter_HistoryInquiry = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int MeCenter_LogOut = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int MeCenter_RealtimeInquiry = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int MeCenter_Title = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int Result_EmptyList = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int Result_Title = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
